apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-aks-csi-weu-01-spc
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
    - objectName: db-user
      key: username
    - objectName: db-pass
      key: password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "<replace-me>"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "kv-aks-csi-weu-01"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: db-user
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: db-pass
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: "<replace-me>"                 # the tenant ID of the KeyVault
